Added heron_control, changed heron_description to use with uuv_simulator
heron/heron pull request #2
Opened 2018-06-27 12:46 UTC by Nirzvi1

2018-07-13 14:27 UTC, tonybaltovski requested changes

2018-07-13 14:27 UTC, tonybaltovski commented on heron_description/CHANGELOG.rst
> +0.4.0 (2018-06-26)
Remove this, it get automatically generated when you use `catkin_generate_changelog`

2018-07-13 14:27 UTC, tonybaltovski commented on heron_description/package.xml
> +  <version>0.4.0</version>
Revert, this is done using `catkin_prepare_release`

2018-07-13 14:27 UTC, tonybaltovski commented on heron_description/urdf/sensors.xacro
> + </gazebo>
Spacing is off.

2018-07-13 14:27 UTC, tonybaltovski commented on heron_description/CMakeLists.txt
> +    heron_msgs
Are `heron_msgs` needed?  I don't see them used any where.

2018-07-13 17:11 UTC, dniewinski commented on heron_description/urdf/base.xacro
> +  <xacro:property name="collision_mesh_file" value="file://$(find heron_description)/meshes/heron_base.stl"/>
Does the simulator use the collision mesh to calculate buoyancy?  If so, simplifying this mesh may go a long way for efficiency

2018-07-13 18:42 UTC, Nirzvi1 commented on heron_description/CMakeLists.txt
> +    heron_msgs
Should I put "roslaunch" back in?

2018-07-16 14:25 UTC, tonybaltovski approved these changes

2018-07-26 15:53 UTC, tonybaltovski commented
@dniewinski any remaining concerns?

2018-07-26 16:09 UTC, david0429 commented
None on my end

2018-07-26 16:12 UTC, dniewinski commented
LGTM

2018-07-26 18:50 UTC, tonybaltovski commented
@Nirzvi1 can you rebase?

2018-07-26 19:31 UTC, merged